airbnb_test=read.csv('airbnb_test_final.csv')
airbnb_test=airbnb_test[,-c(1,13,27)]

#Standardization in testing
airbnb_test$availability_30<-scale(airbnb_test$availability_30,center = TRUE, scale = TRUE)
airbnb_test$availability_365<-scale(airbnb_test$availability_365,center = TRUE, scale = TRUE)
airbnb_test$availability_60<-scale(airbnb_test$availability_60,center = TRUE, scale = TRUE)
airbnb_test$availability_90<-scale(airbnb_test$availability_90,center = TRUE, scale = TRUE)
airbnb_test$bedrooms<-scale(airbnb_test$bedrooms,center = TRUE, scale = TRUE)
airbnb_test$beds<-scale(airbnb_test$beds,center = TRUE, scale = TRUE)
airbnb_test$bathrooms<-scale(airbnb_test$bathrooms,center = TRUE, scale = TRUE)
airbnb_test$cleaning_fee<-scale(airbnb_test$cleaning_fee,center = TRUE, scale = TRUE)
airbnb_test$maximum_nights<-scale(airbnb_test$maximum_nights,center = TRUE, scale = TRUE)
airbnb_test$minimum_nights<-scale(airbnb_test$minimum_nights,center = TRUE, scale = TRUE)
airbnb_test$price<-scale(airbnb_test$price,center = TRUE, scale = TRUE)
airbnb_test$security_deposit<-scale(airbnb_test$security_deposit,center = TRUE, scale = TRUE)
airbnb_test$number_of_amenities<-scale(airbnb_test$number_of_amenities,center = TRUE, scale = TRUE)
airbnb_test$number_of_host_verifications<-scale(airbnb_test$number_of_host_verifications,center = TRUE, scale = TRUE)
airbnb_test$first_review_days<-scale(airbnb_test$first_review_days,center = TRUE, scale = TRUE)
airbnb_test$length_host_about<-scale(airbnb_test$length_host_about,center = TRUE, scale = TRUE)
airbnb_test$guests_included<-scale(airbnb_test$guests_included,center = TRUE, scale = TRUE)
airbnb_test$host_total_listings_count<-scale(airbnb_test$host_total_listings_count,center = TRUE, scale = TRUE)
